---
# CA public certificate ConfigMap — used by containers that need to trust
# the self-signed CA (e.g., ARC DinD runners pushing to Zot over HTTPS).
# The actual ca.crt content should be pasted here after generating the CA.
apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-ca-cert
  namespace: kube-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFUzCCAzugAwIBAgIUQBCzqE5MnKMuu30VI0kfIJgKFGgwDQYJKoZIhvcNAQEL
    BQAwOTEcMBoGA1UEAwwTc2hhbmt5anMtaG9tZWxhYi1jYTEZMBcGA1UECgwQc2hh
    bmt5anMtaG9tZWxhYjAeFw0yNjA0MDYxNzE5MDFaFw0zNjA0MDMxNzE5MDFaMDkx
    HDAaBgNVBAMME3NoYW5reWpzLWhvbWVsYWItY2ExGTAXBgNVBAoMEHNoYW5reWpz
    LWhvbWVsYWIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCHAIh2Qnox
    feLEv1c773t/ZP7Qs0wWwYmRLM/JiPO27dgCKajkK9AXn8ERlYxuZkqmSFGHHrux
    STXilKY3n1zWLtn5JAlVQZPORDpDWwPQwuvtjLSBBCv5jIutny0MoVZKmc2UVi2S
    J34l80pfJu6ATTVWBk2UiVIUBfFzVoojnfuTQ8+5DZ9yM5xz+UFZoIY9CMqCj/T9
    cNaDuH1AkyKGab8Pylk8Hp1yL4KabWONEyMNL0D7pV5KC+b3g2M9RAId5FJjn+Ka
    2X9NkoQ4a/4OUMhDFQgQEy3HHTANaUllGeCdGNPJv8Zb/fcogB1mKBnWKm1LvYt9
    akscveFoQl8zxjy5YZ6KHrP1c8XPsZWGxvi1n5avm1Q3siJBzB2Vc20fYcS4/9OU
    W6oNJqU9pJbL2arikbYGrcqlTUEG0X3FtdMsuu+UVjHyxq6VSOf3P/706SQ5BVMx
    OD+g+sK55D3gFRmXSFeXiAhujQY4sJLWTEOmlhcvnO5Udc/rzswzH4+B+fq9KUfo
    zsxukwuz5mDZ6V/XgE15pz4dwm16db2tFikO5Y2gHDHPW0HJ1qU0/QGF9KyQH1Fk
    7qUf5fJi5TYsvDlV/qValA1FPZss4+kbpx+FT2RImXD3CfEZiZ8j0QIhe1kFmJ/o
    pXBKlKSzCnEVel81T0AEGv4/0RzKMftlVQIDAQABo1MwUTAdBgNVHQ4EFgQUDq0V
    ZCtWhOaw6vXaGHlwWxgBFRcwHwYDVR0jBBgwFoAUDq0VZCtWhOaw6vXaGHlwWxgB
    FRcwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAGA82UE8Pjylg
    MACaeaEaoE80hNUh3JBdJ2XCoTBLxlb5BJscwMSEKC7aNThJknwkjr5FEizLraTE
    2oNIudbKznwhKo030b0H01mCarZ2fSeHcbb2d944p4fPZo9GqdC3huqqrmHBqkqF
    K5RtvHS7maTtqkfr+qlBymhXh3hT4nWi/Z6a7QCJKvI3NMI9osJoqvjxhE/zt4gt
    NwAa9XwIWaj4SYZs1OD8hQnVOA34LEEf7GV1OLMbMIg5iEsEnpMEsZs9L8ZUzOKX
    PgvTqN1EGWd5yk1YsQPAGK1JkIFRTkLrvw4HQcX+ik3IxvK524ifOSvm8v4ttWrQ
    TsMBO/rDNnFEJSTid4oEKo2pxPWw0f4J3NuVGh/xBebIcp4vI9fhE5cDppuZRpdS
    FwK/txVhyxV6LW4/Vmk4o+cBRhHWEoB/fiQkDyvfRleYlbQ3NW7ICU2f9XeCj2Ml
    GFilthF9ykkL4WentKxp3GxUleFqupwvhRLUzdD539wkSqmbxZp70ZWlpfFNZETa
    pktmVwJ/tCY8owNnOEtJZCZ+biZ4bwI0MLxjX02XYzokBFYJzdVbUMnEtfF3jW67
    VGcd2wztqOt3Hr3AP5PYhRRdTkAWs/IeT9dOg8aXcQgGu2ocQ2Yx3YnamhzamX62
    hxYhxGZYaljJCvHM2lB1ze2mO0zwVxk=
    -----END CERTIFICATE-----
