---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: eso
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: paperclip
---
apiVersion: v1
kind: Namespace
metadata:
  name: paperclip-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: rustdesk
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: zot
