---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted

- name: Verify tailscale status
  ansible.builtin.command:
    cmd: tailscale status
  changed_when: false
