---
# Tailscale-only playbook
# Usage: make deploy-tailscale

- name: Configure Tailscale
  hosts: servers
  become: true
  vars:
    ansible_become_pass: "{{ lookup('env', 'BECOME_PASS') }}"
    ansible_ssh_pass: "{{ lookup('env', 'BECOME_PASS') }}"
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
  roles:
    - common
    - tailscale
