---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
  namespace: arc-runners
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
      version: ">=0.9.0"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    githubConfigUrl: "https://github.com/ShankyJS/homelab"
    githubConfigSecret: arc-github-secret
    runnerScaleSetName: "jetson-arm64"
    maxRunners: 3
    minRunners: 0
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
